2023-06-21 18:04:50,810 INFO: Microblog startup [in C:\Users\ASUS\Desktop\first_project\app\__init__.py:82]
2023-06-21 18:04:59,904 ERROR: Exception on / [GET] [in c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\first_project\app\main\routes.py", line 37, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items,
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ASUS\Desktop\first_project\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\ASUS\Desktop\first_project\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\ASUS\Desktop\first_project\app\templates\base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-06-21 18:06:32,187 INFO: Microblog startup [in C:\Users\ASUS\Desktop\first_project\app\__init__.py:82]
2023-06-21 18:06:33,275 ERROR: Exception on / [GET] [in c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\first_project\app\main\routes.py", line 37, in index
    return render_template('main/index.html', title='Home Page', form=form, posts=posts.items,
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main/index.html
2023-06-21 18:06:37,385 ERROR: Exception on / [GET] [in c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\ASUS\Desktop\first_project\app\main\routes.py", line 37, in index
    return render_template('main/index.html', title='Home Page', form=form, posts=posts.items,
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\asus\desktop\first_project\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main/index.html
2023-06-21 18:08:02,056 INFO: Microblog startup [in C:\Users\ASUS\Desktop\first_project\app\__init__.py:82]
